name: Benchmarks
on:
  push:
    branches:
      - "main" # or "master"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v5
        id: install_python
        with:
          python-version: "3.11"

      - name: install poetry
        run: pip install 'poetry==1.8.2'

      - name: install system dependencies
        run: sudo apt-get install -qq -y build-essential libgeos-dev freetds-dev unixodbc-dev

      - name: install ibis
        run: poetry install --without dev --without docs --all-extras

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: poetry run pytest --benchmark-enable ibis/tests/benchmarks
